# Site settings
title: Tom Rolandus Hagedoorn
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://tomrolandus.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tom Rolandus Hagedoorn
user_description: to fill in
user_title: Senior Data Scientist - GenAI
email: tomrolandus@gmail.com
linkedin_username: tom-rolandus-hagedoorn-7a9a192a
github_username: tomrolandus

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
